name: Run Coding Challenges

on:
  push:
    # Triggers the workflow on push event only for the "main" branch
    branches:
      - main

  # Allows to rub this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-atm-withdraw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run AtmWithdraw
        run: |
          cd src/main/kotlin/atmwithdraw
          kotlinc data/* AtmWithdraw.kt Tester.kt -include-runtime -d atmwithdrawtester.jar
          java -jar atmwithdrawtester.jar
