name: Run Coding Challenges

on:
  # Triggers the workflow on push event only for the "main" branch
  push:
    branches:
      - main
  # Triggers the workflow on Pull Requests opened against the "main" branch
  pull_request:
    branches:
      - main

  # Allows to rub this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-atm-withdraw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run AtmWithdraw
        run: |
          cd src/main/kotlin/atmwithdraw
          kotlinc ../utils/* ../common/* data/* AtmWithdraw.kt Tester.kt -include-runtime -d atmwithdrawtester.jar
          java -jar atmwithdrawtester.jar
  run-two-sum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run TwoSum
        run: |
          cd src/main/kotlin/twosum
          kotlinc ../utils/* ../common/* TwoSum.kt Tester.kt -include-runtime -d twosumtester.jar
          java -jar twosumtester.jar
  run-valid-parentheses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ValidParentheses
        run: |
          cd src/main/kotlin/validparentheses
          kotlinc ../utils/* ../common/* data/* ValidParentheses.kt Tester.kt -include-runtime -d validparenthesestester.jar
          java -jar validparenthesestester.jar
  run-first-bad-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run FirstBadVersion
        run: |
          cd src/main/kotlin/firstbadversion
          kotlinc ../utils/* ../common/* VersionControl.kt FirstBadVersion.kt Tester.kt -include-runtime -d firstbadversiontester.jar
          java -jar firstbadversiontester.jar
  run-ransom-note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run RansomNote
        run: |
          cd src/main/kotlin/ransomnote
          kotlinc ../utils/* ../common/* RansomNote.kt Tester.kt -include-runtime -d ransomnotetester.jar
          java -jar ransomnotetester.jar
  run-maximum-subarray:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run MaximumSubarray
        run: |
          cd src/main/kotlin/maximumsubarray
          kotlinc ../utils/* ../common/* MaximumSubarray.kt Tester.kt -include-runtime -d maximumsubarraytester.jar
          java -jar maximumsubarraytester.jar
  run-insert-interval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run InsertInterval
        run: |
          cd src/main/kotlin/insertinterval
          kotlinc ../utils/* ../common/* InsertInterval.kt Tester.kt -include-runtime -d insertintervaltester.jar
          java -jar insertintervaltester.jar
  run-binary-search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run BinarySearch
        run: |
          cd src/main/kotlin/binarysearch
          kotlinc ../utils/* ../common/* BinarySearch.kt Tester.kt -include-runtime -d binarysearchtester.jar
          java -jar binarysearchtester.jar
  run-linked-list-cycle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run LinkedListCycle
        run: |
          cd src/main/kotlin/linkedlistcycle
          kotlinc ../utils/* ../common/* LinkedListCycle.kt Tester.kt -include-runtime -d linkedlistcycletester.jar
          java -jar linkedlistcycletester.jar
  run-01-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run 01Matrix
        run: |
          cd src/main/kotlin/matrix01
          kotlinc ../utils/* ../common/* Matrix01.kt Tester.kt -include-runtime -d matrix01tester.jar
          java -jar matrix01tester.jar
  run-k-closes-points-to-origin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run KClosestPointsToOrigin
        run: |
          cd src/main/kotlin/kclosestpointstoorigin
          kotlinc ../utils/* ../common/* KClosestPointsToOrigin.kt Tester.kt -include-runtime -d kclosestpointstoorigintester.jar
          java -jar kclosestpointstoorigintester.jar
  run-longest-unique-substring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run LongestSubstringWithoutRepeatingCharacters
        run: |
          cd src/main/kotlin/longestuniquesubstring
          kotlinc ../utils/* ../common/* LongestUniqueSubstring.kt Tester.kt -include-runtime -d longestuniquesubstringtester.jar
          java -jar longestuniquesubstringtester.jar
  run-three-sum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run 3Sum
        run: |
          cd src/main/kotlin/threesum
          kotlinc ../utils/* ../common/* ThreeSum.kt Tester.kt -include-runtime -d threesumtester.jar
          java -jar threesumtester.jar
  run-bst-lca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run LowestCommonAncestor
        run: |
          cd src/main/kotlin/lowestcommonancestorbst
          kotlinc ../utils/* ../common/* LowestCommonAncestorBST.kt Tester.kt -include-runtime -d lowestcommonancestorbsttester.jar
          java -jar lowestcommonancestorbsttester.jar
  run-balanced-binary-tree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run BalancedBinaryTree
        run: |
          cd src/main/kotlin/balancedbinarytree
          kotlinc ../utils/* ../common/* BalancedBinaryTree.kt Tester.kt -include-runtime -d balancedbinarytreetester.jar
          java -jar balancedbinarytreetester.jar
  run-add-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run AddBinary
        run: |
          cd src/main/kotlin/addbinary
          kotlinc ../utils/* ../common/* AddBinary.kt Tester.kt -include-runtime -d addbinarytester.jar
          java -jar addbinarytester.jar
  run-clone-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run CloneGraph
        run: |
          cd src/main/kotlin/clonegraph
          kotlinc ../utils/* ../common/* CloneGraph.kt Tester.kt -include-runtime -d clonegraphtester.jar
          java -jar clonegraphtester.jar
  run-course-schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run CourseSchedule
        run: |
          cd src/main/kotlin/courseschedule
          kotlinc ../utils/* ../common/* CourseSchedule.kt Tester.kt -include-runtime -d coursescheduletester.jar
          java -jar coursescheduletester.jar
  run-trie-implementation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run trieprefixtree
        run: |
          cd src/main/kotlin/trieprefixtree
          kotlinc ../utils/* ../common/* Trie.kt Tester.kt -include-runtime -d trieprefixtreetester.jar
          java -jar trieprefixtreetester.jar
  run-coin-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run CoinChange
        run: |
          cd src/main/kotlin/coinchange
          kotlinc ../utils/* ../common/* CoinChange.kt Tester.kt -include-runtime -d coinchangetester.jar
          java -jar coinchangetester.jar
  run-number-of-islands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run NumberOfIslands
        run: |
          cd src/main/kotlin/numberofislands
          kotlinc ../utils/* ../common/* NumberOfIslands.kt Tester.kt -include-runtime -d numberofislandstester.jar
          java -jar numberofislandstester.jar
