name: Run Coding Challenges

on:
  # Triggers the workflow on push event only for the "main" branch
  push:
    branches:
      - main
  # Triggers the workflow on Pull Requests opened against the "main" branch
  pull_request:
    branches:
      - main

  # Allows to rub this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-atm-withdraw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run AtmWithdraw
        run: |
          cd src/main/kotlin/atmwithdraw
          kotlinc ../utils/* data/* AtmWithdraw.kt Tester.kt -include-runtime -d atmwithdrawtester.jar
          java -jar atmwithdrawtester.jar
  run-two-sum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run TwoSum
        run: |
          cd src/main/kotlin/twosum
          kotlinc ../utils/* TwoSum.kt Tester.kt -include-runtime -d twosumtester.jar
          java -jar twosumtester.jar
  run-valid-parentheses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ValidParentheses
        run: |
          cd src/main/kotlin/validparentheses
          kotlinc ../utils/* data/* ValidParentheses.kt Tester.kt -include-runtime -d validparenthesestester.jar
          java -jar validparenthesestester.jar
  run-first-bad-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run FirstBadVersion
        run: |
          cd src/main/kotlin/firstbadversion
          kotlinc ../utils/* VersionControl.kt FirstBadVersion.kt Tester.kt -include-runtime -d firstbadversiontester.jar
          java -jar firstbadversiontester.jar
  run-ransom-note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run RansomNote
        run: |
          cd src/main/kotlin/ransomnote
          kotlinc ../utils/* RansomNote.kt Tester.kt -include-runtime -d ransomnotetester.jar
          java -jar ransomnotetester.jar
  run-maximum-subarray:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run MaximumSubarray
        run: |
          cd src/main/kotlin/maximumsubarray
          kotlinc ../utils/* MaximumSubarray.kt Tester.kt -include-runtime -d maximumsubarraytester.jar
          java -jar maximumsubarraytester.jar
  run-insert-interval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run InsertInterval
        run: |
          cd src/main/kotlin/insertinterval
          kotlinc ../utils/* InsertInterval.kt Tester.kt -include-runtime -d insertintervaltester.jar
          java -jar insertintervaltester.jar
  run-binary-search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run BinarySearch
        run: |
          cd src/main/kotlin/binarysearch
          kotlinc ../utils/* BinarySearch.kt Tester.kt -include-runtime -d binarysearchtester.jar
          java -jar binarysearchtester.jar
  run-linked-list-cycle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run LinkedListCycle
        run: |
          cd src/main/kotlin/linkedlistcycle
          kotlinc ../utils/*  ../common/* LinkedListCycle.kt Tester.kt -include-runtime -d linkedlistcycletester.jar
          java -jar linkedlistcycletester.jar
