name: Run Coding Challenges

on:
  push:
    # Triggers the workflow on push event only for the "main" branch
    branches:
      - main

  # Allows to rub this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-atm-withdraw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run AtmWithdraw
        run: |
          cd src/main/kotlin/atmwithdraw
          kotlinc data/* AtmWithdraw.kt Tester.kt -include-runtime -d atmwithdrawtester.jar
          java -jar atmwithdrawtester.jar
  run-two-sum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run TwoSum
        run: |
          cd src/main/kotlin/twosum
          kotlinc TwoSum.kt Tester.kt -include-runtime -d twosumtester.jar
          java -jar twosumtester.jar
  run-valid-parentheses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ValidParentheses
        run: |
          cd src/main/kotlin/validparentheses
          kotlinc data/* ValidParentheses.kt Tester.kt -include-runtime -d validparenthesestester.jar
          java -jar validparenthesestester.jar
  run-first-bad-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run FirstBadVersion
        run: |
          cd src/main/kotlin/firstbadversion
          kotlinc VersionControl.kt FirstBadVersion.kt Tester.kt -include-runtime -d firstbadversiontester.jar
          java -jar firstbadversiontester.jar
